apiVersion: v1
kind: Service
metadata:
  labels:
    opensearch.cluster.dashboards: my-first-cluster
  name: my-first-cluster-dashboards-lb
spec:
  type: LoadBalancer
  ports:
  - name: dashboard
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    opensearch.cluster.dashboards: my-first-cluster
---
apiVersion: v1
kind: Service
metadata:
  labels:
    opensearch.cluster.dashboards: my-first-cluster
  name: my-first-cluster-dashboards-node
spec:
  type: LoadBalancer
  ports:
  - name: node
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    opster.io/opensearch-cluster: my-first-cluster
